<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTpov9in\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTpov9in/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTpov9in.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTpov9in\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTpov9in\appDevDebugProjectContainer([
    'container.build_hash' => 'Tpov9in',
    'container.build_id' => '30089a4b',
    'container.build_time' => 1612697621,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTpov9in');
